---
- name: Install apache
  apt: 
    name: apache2 
    state: latest
  notify: restart apache

- name: stat indexhtml #https://stackoverflow.com/questions/24162996/how-to-move-rename-a-file-using-an-ansible-task-on-a-remote-system
  stat: path=/var/www/html/index.html
  register: foo_stat

- name: Move foo to bar
  command: mv /var/www/html/index.html /var/www/
  when: foo_stat.stat.exists