---
- name: "prerequisite"
  package:
    name: software-properties-common
    state: latest
- name: "Add repository for PHP 7.3."
  apt_repository: 
    repo: ppa:ondrej/php
- name: Install php
  package:
    name:
      - php7.3
      - php7.3-common
      - php7.3-opcache
      - php7.3-cli
      - php7.3-gd
      - php7.3-curl
      - php7.3-mysql
      - php7.3-zip
      - php7.3-xml
      - php7.3-mbstring
    state: latest
  notify: restart php
