---
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    notify: restart composer

- name: Run Composer installer.
  command: >
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer -y

- name: Composer update.
  command: >
    composer self-update -y

- name: Composer require phpunit.
  command: >
    composer require --dev phpunit/phpunit
