---
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer

- name: Composer update.
  command: >
    composer self-update

- name: Composer require phpunit.
  command: >
    composer require --dev phpunit/phpunit -d /var/applicatie/

- name: Composer AWS SDK.
  command: >
    composer require aws/aws-sdk-php -d /var/applicatie/

- name: Composer install vendor.
  command: >
    composer install -d /var/applicatie/
