---
php_version: '7.3'

varregexp: '<div class="carousel-inner">'
varreplace: | 
  <div class="carousel-inner">
  <?php
    require '/var/www/html/vendor/autoload.php';
        use \Aws\S3\S3Client;
        use \Aws\S3\Exception\S3Exception;

        $bucket = 's3phpimages2';
        $s3 = new S3Client([
                'version' => 'latest',
                'region'  => 'us-east-1'
        ]);
        try {
                $images = $s3->getIterator('ListObjects', array(
                        'Bucket' => $bucket
                        //'Delimiter' => '/',
                        //'Prefix' => '/images/'
                ));
                $name = array();
                foreach ($images as $photos){
                        $names = $photos['Key'];
                        array_push($name, $names);
                }
                foreach($name as $key => $image){
                        echo ($key == 0) ? '<div class="carousel-item active">' : '<div class="carousel-item">';
                        echo "<img class='d-block w-100' src='//s3phpimages.s3.amazonaws.com/$image'/></div>";
                        }
                } catch (S3Exception $e) { echo $e->getMessage() . PHP_EOL;
          }
    ?>
  </div>
  <div class="former-carouselclass">